### ISSUE TITLE
Malformed config file in readme file

### ISSUE THREAD

**Issue by djryan012** [spacemanspiff2007/home-assistant-artnet#1]
Hassio 79.3. I have artnet.py installed in custom_components/lights. Just copied your example and put it into my lights config file and get this error. Malformed yaml format I what this is telling me.

Invalid config for [light.artnet]: required key not provided @ data['devices']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/light.artnet/

**Comment by spacemanspiff2007** [comment]
Have you had the old artnet integration running? if so a restart is required.
I just check it and for me it does not show any error.
Can you try again with the current version?

**Comment by spacemanspiff2007** [comment]
@djryan012 : Does this issue still persist?

**Comment by djryan012** [comment]
I was using the old artnet before running yours. I have not yet had the chance to try again with your version. Sorry for the delay in response.

**Comment by djryan012** [comment]
I had restarted when I tried your config. Tried again by changing to your artnet.py file and config at the same time then restarted hassio without running config check. Ran a config check after the restart with no error messages.
