### ISSUE TITLE
Idea for audio controlled DMX

### ISSUE THREAD

**Issue by RolandWijnen** [spacemanspiff2007/home-assistant-artnet#2]
Hi spacemanspiff2007, 

I'm using your artnet code in Home Assistant to control all of my garden lights. It works great! Thansk for this piece of software. 

I was wondering if an audiosignal (music) can be used to drive the artnet signal going to my DMX controllers. Not a high priority for my Smart Living system, but would be a nice gimmick in the summer during a party/long summer evening. I use an XAP400 mixer to route audio around the house and garden. The sound is also fed into my Raspberry Pi, running hassio. So, I guess in theory it could be processed and used to drive the artnet signal. Have you ever considered this? Cheers, Roland.

**Comment by spacemanspiff2007** [comment]
It sure could be done and would be nice but I think this is something which should be built on top of the PyArtNet library. I am very busy right now so I can not support you with this complex task - sorry.
But you can always use the existing code and try for yourself. :+1:

**Comment by RolandWijnen** [comment]
Thanks for your quick reply and pointing me in the right direction. I will look into this.
